kind: pipeline
name: default
type: docker

steps:
  - name: test
    image: gradle:8.12-jdk21-jammy
    commands:
      - gradle --no-daemon test
  - name: publish
    image: gradle:8.12-jdk21-jammy
    environment:
      ARTEFACTS_USER:
        from_secret: ARTEFACTS_USER
      ARTEFACTS_PASSWORD:
        from_secret: ARTEFACTS_PASSWORD
    commands:
      - export BUILD_NUMBER=${DRONE_BUILD_NUMBER}
      - gradle --no-daemon publish
    when:
      ref:
        - refs/heads/master
