kind: pipeline
name: default
type: docker

steps:
  - name: test
    image: gradle:6.7.1-jdk11
    commands:
      - gradle test
  - name: publish
    image: gradle:6.7.1-jdk11
    environment:
      ARTEFACTS_USER:
        from_secret: ARTEFACTS_USER
      ARTEFACTS_PASSWORD:
        from_secret: ARTEFACTS_PASSWORD
    commands:
      - gradle publish
    when:
      branch:
        - master
