kind: pipeline
name: default
type: docker

steps:
  - name: test
    image: gradle:7.6-jdk17-focal
    commands:
      - ./gradlew test
  - name: publish
    image: gradle:7.6-jdk17-focal
    environment:
      ARTEFACTS_USER:
        from_secret: ARTEFACTS_USER
      ARTEFACTS_PASSWORD:
        from_secret: ARTEFACTS_PASSWORD
    commands:
      - ./gradlew publish
    when:
      ref:
        - refs/heads/master
