dist: xenial
language: java

jdk:
  - openjdk11

addons:
  sonarcloud:
    organization: $SONAR_ORG_KEY
    projectKey: $SONAR_PROJECT_KEY

before_cache:
  - rm -f  ~/.gradle/caches/modules-2/modules-2.lock
  - rm -fr ~/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - ~/.gradle/caches/
    - ~/.gradle/wrapper/

jobs:
  include:
    - stage: test
      script: ./gradlew test
    - stage: publish artefacts
      if: branch = master
      script: ./gradlew publish
    - stage: analisys
      script: sonar-scanner
