language: java

jdk:
  - openjdk8

cache:
  directories:
    - /home/travis/.ant/

jobs:
  include:
    - stage: test
      script: ant test
    - stage: publish artefacts
      if: branch = master
      script: ant publish
