dist: xenial
language: java

jdk:
  - openjdk11

cache:
  directories:
    - /home/travis/.ant/

before_install:
  - ./resources/install-ant.sh

jobs:
  include:
    - stage: test
      script: ~/.ant/ant/bin/ant test
    - stage: publish artefacts
      if: branch = master
      script: ~/.ant/ant/bin/ant publish
